### ISSUE TITLE
Failed to match input token

### ISSUE THREAD

**Issue by pixybaba** [itod/pegkit#21]
1. Downloaded Zip of PegKit
2. Downloaded Zip of templateengine
3. Opened the workspace of PegKit andadded templateengine project in that workspace
4. Ran ParseGenApp target and generated code for minmath grammar successfully
5. Ran ParseGenApp target and generated code for mysql grammar but got error

Failed to match next input token: Line : 3
Near : @ singleLineComments 
Expected : Word

Found : @

Any reason why?
mysql grammar works, if the code is downloaded from http://itod.github.io/PEGKitMiniMathTutorial/

**Comment by itod** [comment]
This is a tokenizer directive:  `@singleLineComments`

Those were supported by ParseKit, but are not supported by PEGKit. Search
the PEGKit project for  “.grammar” files for examples of how to create a
grammar for PEGKit

TD
