### ISSUE TITLE
Question about how the parser works?

### ISSUE THREAD

**Issue by drekka** [itod/pegkit#31]
I'm not sure if I'm missing something or not. If I have an expression like this:

type = class | protocol;
class = '[' Word ']';
protocol = '<' Word '>';

When passing "[MyClass]..." I would like to get back (on the stack) "[MyClass]", but at the moment I'm getting "[", "MyClass", "]". 

I'm wondering if there is something in the syntax that tells the parser to add the combined values to the stack as a single token.

Another question: When looking at tokens on the stack, is there a way to find the name of the expression that matched in the grammar. Ie. in the above, to get back 'class', or 'protocol, or 'type'.

**Comment by itod** [comment]
On Wed, Jun 24, 2015 at 1:45 AM, Derek Clarkson <notifications@github.com>
wrote:

> I'm not sure if I'm missing something or not. If I have an expression like
> this:
>
> type = class | protocol;
> class = '[' Word ']';
> protocol = '<' Word '>';
>
> When passing "[MyClass]..." I would like to get back (on the stack)
> "[MyClass]", but at the moment I'm getting "[", "MyClass", "]". I'm
> wondering if there is something in the syntax that tells the parser to add
> the combined values to the stack as a single token.
>

No there's not. This is not desirable, as it would be difficult and
confusing to configure. This is what your Action or Delegate callback is
for. Pop the tokens you want and work on them there.

>  Another question: When looking at tokens on the stack, is there a way to
> find the name of the expression that matched in the grammar. Ie. in the
> above, to get back 'class', or 'protocol, or 'type'.
>
Generally, you would know which Action or Delegate callback you are in, so
you can just produce or hardcode the string there. This would be better
than the extra overhead of a string most people will never use. If you want
to have totally generic Delegate callback methods (it doesn't sound like it
from your question above, but say you did), you can configure the
ParserGenApp to produce these with the "Pre/Post Match Callbacks: ON
SYNTAX" option. Try experimenting with that.

TD

**Comment by drekka** [comment]
Thanks. I got it working with calls backs on the relevant expressions. But now I'm reconfiguring to use a delegate instead so that the grammar is cleaner.
