### ISSUE TITLE
Using throws to indicate end of parse 

### ISSUE THREAD

**Issue by drekka** [itod/pegkit#40]
Hi

During some debugging of my code I activated a generate exception symbolic breakpoint and noticed that PEGKit appears to be using exceptions internally to indicate that it's failed to match part of the grammar. Specifically in

    -[PKParser match:(NSInteger)tokenKind discard:(BOOL)discard]

In my code it appears to be failing to match a key path name which is correct as the string I'm parsing doesn't contain one. I don't get any exceptions throw to my code and tracing back through the stack I can see a try-catch which will kick in.

I've always understood that it's better to populate NSError ** pointers because it's expensive to throw exceptions, so I'm wondering if a code improvement might be to replace the usage of throws on match failures with NSError** pointers. Then in higher parts of the code, it can decide if there is an actual error and throw it, or that it's just that the grammar is not matching and it should proceed to the next match attempt.

Alternatively it could be that my grammar is not as good as I think and needs to be adjusted so the internal exceptions are not generated.

**Comment by itod** [comment]
This is expected (and desirable) behavior. See here: https://github.com/itod/pegkit/issues/41#issuecomment-255787407

Also, PEGKit actually already follows your advice of returning an out NSError pointer. After using Exceptions for internal, recursive, control flow (again, see link above), PEGKit *does* convert a thrown exception to an out NSError pointer which is returned to clients. 

For the implementation of this, see: `-[PKParser parse:]`
